package swdchatbox.modules.chat.dto.response;

import lombok.Builder;
import lombok.Getter;

import java.util.List;

/**
 * Full response for a chat turn: the user's message and the AI answer (with citations).
 * Use {@code userMessage.role} ({@code USER}) and {@code assistantMessage.role} ({@code ASSISTANT})
 * to tell the two sides apart.
 */
@Getter
@Builder
public class ChatAnswerResponse {

    /** Message sent by the user ({@code role = USER}). */
    private MessageResponse userMessage;

    /** Answer generated by the AI bot ({@code role = ASSISTANT}). */
    private MessageResponse assistantMessage;

    private List<CitationResponse> citations;
}
