name: swdchatbox

services:
  mysql:
    image: mysql:8.4
    container_name: swdchatbox

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - swdchatbox:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

volumes:
  swdchatbox: